### create post(후기)
POST http://localhost:8080/post
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file", filename="skull.png"
Content-Type: image/png

< ./skull.png
--WebAppBoundary
Content-Disposition: form-data; name="postForm"
Content-Type: application/json

{
  "title": "title",
  "content": "content",
  "tripGroupId": 2
}


### create post(후기) without image
POST http://localhost:8080/post
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3MiLCJlbWFpbCI6I...

--WebAppBoundary
Content-Disposition: form-data; name="file", filename="skull.png"
Content-Type: image/png

< ./skull.png
--WebAppBoundary
Content-Disposition: form-data; name="postForm"
Content-Type: application/json

{
  "title": "title",
  "content": "content",
  "tripGroupId": 1
}


### Read post list 기본
GET http://localhost:8080/post/list


### Read post list 부산
GET http://localhost:8080/post/list?area=busan


### Update post (로그인 후)
PATCH http://localhost:8080/post/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ...

{
  "title": "new title",
  "content": "new content"
}


### Delete post (로그인 후)
DELETE http://localhost:8080/post/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ...
