### create post(후기)
POST http://localhost:8080/post
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file", filename="skull.png"
Content-Type: image/png

< ./skull.png
--WebAppBoundary
Content-Disposition: form-data; name="postForm"
Content-Type: application/json

{
  "title": "title",
  "content": "content",
  "tripGroupId": 1
}


### create post(후기) without image
POST http://localhost:8080/post
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3MiLCJlbWFpbCI6I...

--WebAppBoundary
Content-Disposition: form-data; name="file", filename="skull.png"
Content-Type: image/png

< ./skull.png
--WebAppBoundary
Content-Disposition: form-data; name="postForm"
Content-Type: application/json

{
  "title": "title",
  "content": "content",
  "tripGroupId": 1
}