name: Tweaver Docker Image CI

on:
  push:
    branches: [ "master" ]

  # 개발서버 구축 이후 pr 오픈
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: My first step
      uses: ./.github/actions/docker-image.yml

    # 1. Java 17 세팅: 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 2. Gradle 세팅
    - name: Init Gradle
      uses: gradle/gradle-build-action67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        gradle-version: 8.6

    # 3. Tweaver 빌드하기
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean bootJar

    # 4. Docker image 빌드하기
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag github-actions/tweaver

    # 5. Docker 로그인 하기
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PW }}

    # 6. Docker 푸시하기
    - name: docker Hub push
      run: docker push github-action/tweaver
