name: Tweaver Docker Image CI

on:
  push:
    branches: [ "master" ]

  # 개발서버 구축 이후 pr 오픈
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Tweaver 빌드하기
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean bootJar

    # 2. Docker image 빌드하기
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag github-actions/tweaver

    # 3. Docker 로그인 하기
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PW }}

    # 4. Docker 푸시하기
    - name: docker Hub push
      run: docker push github-action/tweaver
