name: Tweaver Docker Image CI

on:
  push:
    branches: [ "master" ]

  # 개발서버 구축 이후 pr 오픈
  # pull_request:
  #   branches: [ "master" ]
permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: My First Checkout
      uses: actions/checkout@v3

    # 1. Java 17 세팅: 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: make application.yml
      run: |
        # create application-prod.yml
        cd ./src/main/resources
        
        # application-database.yaml 파일 생성
        touch ./application.yml
        
        # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
        echo "${{ secrets.APPLICATION_PROD }}" >> ./application.yml
      shell: bash

    # 2. Gradle 세팅
    - name: Init Gradle
      uses: gradle/gradle-build-action67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        gradle-version: 8.6

    # Gradle Build를 위한 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 3. Tweaver 빌드하기
    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test

    # 4. Docker image 빌드하기
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag github-actions/tweaver

    # 5. Docker 로그인 하기
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PW }}

    # 6. Docker 푸시하기
    - name: docker Hub push
      run: docker push github-action/tweaver
