name: Tweaver Docker Image CI

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: My First Checkout
      uses: actions/checkout@v3

    # 1. Java 17 세팅:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 2. application.yml 파일 생성
    - name: make application.yml
      run: |
        # application.yml 파일 생성
        # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
        cd ./src/main/resources
        
        touch ./application.yml
        
        echo "${{ secrets.APPLICATION_PROD }}" >> ./application.yml
      shell: bash

    # 3. Gradle Build를 위한 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 4. Tweaver 빌드하기
    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test

    # 5. Docker image 빌드하기
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_ID }}/tweaver

    # 6. Docker 로그인 하기
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PW }}

    # 7. Docker 푸시하기
    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_ID }}/tweaver
